site_name: "Imageomics Guide"
site_description: "A guide to collaborative work for Imageomics, including GitHub and Hugging Face workflows."
site_author: "Imageomics Institute"
site_url: "https://Imageomics.github.io/Imageomics-guide/"
edit_uri: view/main/docs

repo_url: https://github.com/Imageomics/Imageomics-guide
edit_uri: blob/main/docs/

theme:
  name: material
  icon:
    view: material/eye
  logo: logos/Imageomics_logo_butterfly.png
  favicon: logos/Imageomics_logo_butterfly.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.view
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Imageomics
    - icon: simple/huggingface
      link: https://huggingface.co/imageomics
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/imageomics-institute
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/imageomics
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/imageomics/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ImageomicsInstitute/videos
    - icon: octicons/link-16
      link: https://imageomics.org

copyright: >
  The Imageomics Institute is supported by the National Science Foundation under Award No. 2118240 "HDR Institute: Imageomics: A New Frontier of Biological Information Powered by Knowledge-Guided Machine Learning." Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation.

plugins:
  - glightbox
  - macros
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
      title: ðŸ“– On This Page

nav:
  - Home: index.md
  - GitHub Guide:
      - "Repo Guide": wiki-guide/GitHub-Repo-Guide.md
      - "Workflow": wiki-guide/The-GitHub-Workflow.md
      - "Pull Request Guide": wiki-guide/The-GitHub-Pull-Request-Guide.md
      - "Projects Guide": wiki-guide/Guide-to-GitHub-Projects.md
      - "Branch Protections": wiki-guide/When-to-think-about-branch-protections.md
      - "Two Repo Problem": wiki-guide/Two-Repo-Problem.md
      - "Why Use the Institute GitHub": wiki-guide/Why-use-the-Institute-GitHub.md
  - Hugging Face Guide:
      - "Repo Guide": wiki-guide/Hugging-Face-Repo-Guide.md
      - "Workflow": wiki-guide/The-Hugging-Face-Workflow.md
      - "Dataset Upload Guide": wiki-guide/The-Hugging-Face-Dataset-Upload-Guide.md
      - "Why Use the Institute Hugging Face": wiki-guide/Why-use-the-Institute-Hugging-Face.md
  - Metadata Guide: 
      - "Metadata Guide": wiki-guide/Metadata-Guide.md
      - "DOI Generation": wiki-guide/DOI-Generation.md
  - Templates:
      - "About Templates": wiki-guide/About-Templates.md
      - "Dataset Card Template": wiki-guide/HF_DatasetCard_Template_mkdocs.md
      - "Model Card Template": wiki-guide/HF_ModelCard_Template_mkdocs.md
  - Command Line Cheat Sheet: wiki-guide/Command-Line-Cheat-Sheet.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Other Resources:
      - "Glossary for Imageomics": wiki-guide/Glossary-for-Imageomics.md
      - "Handling API Keys": wiki-guide/Handling-API-Keys.md
      - "Helpful Tools": wiki-guide/Helpful-Tools-for-your-Workflow.md
      - "Technical Infrastructure": wiki-guide/Technical-Infrastructure.md
      - "Virtual Environments": wiki-guide/Virtual-Environments.md
